server:
  port: 8080


spring:
  application:
    name: boot-spark
  datasource:
    username: root
    password: 1102m6514
    url: jdbc:mysql://127.0.0.1:3306/dbname?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  type-aliases-package: com.yankaizhang.bootspark.entity
#  configuration:
#    map-underscore-to-camel-case: true